apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
    spec:
      containers:
      - name: my-k8s-app
        image: yashodaadarsh/my-k8s-cicd-app:latest  # your Docker Hub image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080